CC = g++

all: primes1 primes2 primes3

primes1: primes1.cpp
	$(CC) primes1.cpp -o primes1

primes2: primes2.cpp
	$(CC) primes2.cpp -o primes2

primes3: primes3.cpp
	$(CC) primes3.cpp -o primes3

clean:
	rm primes1 primes2 primes3